name: snake
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  audioplayers: ^6.0.0
  dependencies:
  flutter_gifimage: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/videos/snake.gif

    

  
    
