name: snake
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.3
  window_size: ^0.1.0
    
    


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  audioplayers: ^6.0.0
  gif: ^2.3.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/videos/snake.gif
    - assets/sounds/tail.png
    - assets/sounds/background_music.mp3
    - assets/sounds/lost_life.mp3
    - assets/sounds/stone.png

    

  
    
